import type { Metadata } from "next";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {darkTheme} from "@/app/dark.theme";
import {ThemeProvider, CssBaseline, Container} from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <AppRouterCacheProvider>
              <ThemeProvider theme={darkTheme}>
                  <CssBaseline />
                  <Container>
                      {children}
                  </Container>
              </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
